function y=segmentationRange(x,minThreshold,maxThreshold)
    BW=(x(:,:,1)>=minThreshold(1))&(x(:,:,1)<=maxThreshold(1))&...
        (x(:,:,2)>=minThreshold(2))&(x(:,:,2)<=maxThreshold(2))&...
        (x(:,:,3)>=minThreshold(3))&(x(:,:,3)<=maxThreshold(3));
%     BW=(x(:,:,1)>=minThreshold(1))&(x(:,:,1)<=maxThreshold(1))&...
%         (x(:,:,2)>=minThreshold(2))&(x(:,:,2)<=maxThreshold(2));
    y=BW;
end