function [BW,maskedImage] = segmentImageGray(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 02-Oct-2016
%----------------------------------------------------


% Convert from RGB to grayscale.
X = rgb2gray(X);

% Create empty mask.
BW = false(size(X));

% Flood fill
row = 29;
column = 59;
tolerance = 28;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 24;
column = 81;
tolerance = 19;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 18;
column = 78;
tolerance = 19;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 45;
column = 66;
tolerance = 19;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 63;
column = 51;
tolerance = 19;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 74;
column = 198;
tolerance = 19;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 81;
column = 198;
tolerance = 28;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 89;
column = 199;
tolerance = 28;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 11;
column = 91;
tolerance = 28;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 13;
column = 83;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 128;
column = 137;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 143;
column = 119;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 132;
column = 105;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 140;
column = 94;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 117;
column = 165;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 137;
column = 146;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 129;
column = 121;
tolerance = 8;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;